apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-cloud-deployment # Change to your actual deployment name
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
